### ISSUE TITLE
TypeError: parse Bearer Token is not a function Version 1.0.1

### ISSUE THREAD

**Issue by tbudhe** [stephenmathieson/node-parse-bearer-token#10]
[npm Run Kit](https://npm.runkit.com/parse-bearer-token)

> TypeError: parse Bearer Token is not a function Version 1.0.1

 ```javascript  var parseBearerToken = require("parse-bearer-token");
var req = {
'Accept':'application/json',
'Content-Type':'application/json',
'Authorization':'Bearer {{the-access-token-copied-from-postman}}'
}
let token = parseBearerToken(req);
  if (!token) {
  console.log(`Token Not Exist`);
  }else{
  console.log('Yess');
  }
```
![parse-token-exception](https://user-images.githubusercontent.com/17787642/70083368-40a79600-15da-11ea-9b69-9fb4e2f8a1aa.png)

I have check this npm code, issue of hoisting. Please fix and let us know. I love this package. 

Thanks for creating this package.

**Comment by stephenmathieson** [comment]
It's a "module" now. Do:

```js
var parseBearerToken = require('parse-bearer-token').default
```

I'll add something to the README 👍
